### ISSUE TITLE
Bioconda recipe

### ISSUE THREAD

**Issue by natir** [hnikaein/stark#1]
Hello thank for your work on stark

I would like to create a bioconda recipe for stark but I need a release. Can you create a release with any version number?

Thanks

**Comment by hnikaein** [comment]
Hello,

Done, and sorry for late response.

Please check the build folder and let me know if I should do anything else.

Thanks.

**Comment by natir** [comment]
Hello,

Sorry I wasn't clear enough, to create a bioconda recipe, I need a stable url to download the sources of a specific version.

By creating a github release or by tagging a commit git you create this url.

Thanks for your help

**Comment by hnikaein** [comment]
Hello,

Sorry, I've forgot to create the tag. Now it have been pushed.

Thanks
