### ISSUE TITLE
saving binaries in your repo is risky

### ISSUE THREAD

**Issue by ekg** [hnikaein/stark#3]
First, thanks for this awesome tool. It seems like you've really solved this problem!

I thought I'd make a note about a potential problem. If, for every release, you add a new binary to the repo, ultimately, anyone who clones your repository will need to download the entire git tree, which will include all versions of these static binaries. This might get big, and you can't easily purge these from your git tree. This is way, in general, it's better to make releases using the github system, or on a private website that you link to.

(Maybe here, the size of the binary will always be small. If so, perhaps you can get away with releasing it in the repo. I just thought I'd raise a flag because this issue has bitten me in the past.)

**Comment by ekg** [comment]
I also noted that your binary is not static:

```
-> % ldd build/linux_amd64/stark-0.1.1
        linux-vdso.so.1 (0x00007ffd839f0000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2126427000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f212640c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f212621a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f21260cb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2126627000)
```

It will probably work on most modern linuxes. You'll need to change your compile flags to include the static libc if you want to make a static library.

**Comment by hnikaein** [comment]
Thanks.
